config:
  build_jobs: 6
  build_stage:
  db_lock_timeout: 20
  extensions:
  install_tree:
    root:
    projections:
      all: '{name}/{version}/{compiler.name}/{hash}' 
  module_roots:
    tcl: 
  source_cache:
  misc_cache:
  template_dirs:
  - $spack/templates
